### ISSUE TITLE
Complete Battle Maps

### ISSUE THREAD

**Issue by VarunS1997** [Project-Hedron/Issues-and-Tasks#92]
Session Maps almost work at the level we want.

We need to do a few small things to finish them up:

- [ ] Add the ability to add random props or artwork
- [ ] Increase the types of patterns available (see below)
- [ ] Add the abilities for parts of the map to impose benefits/penalties automatically
- [ ] Add more texture presets (see below)

The available patterns that would be good to add:
 - [ ] Fractals (See if we can find a general equation that allows customizable fractals)
 - [ ] Spirals
 - [ ] Burst (high values in the center, tapering towards edges)

Some useful texture presets we should have:
 - [ ] Tiling/Bricks
 - [ ] Grasslands
 - [ ] Water
